### ISSUE TITLE
sed command misses some important substitutions in pyenv-init

### ISSUE THREAD

**Issue by davised** [macdub/pyenv-multiuser#10]
Hi there,

I was having problems getting the `pyenv init -` command to work properly after installing the pyenv-multiuser plugin because the shims in my home dir were getting removed from my `$PATH` and just those in the `$PYENV_ROOT` dir were getting found.

I looked in the source for this plugin and found the sed command that was being run:

https://github.com/macdub/pyenv-multiuser/blob/aabee561cc94feb58c9c3ab881fd4290c39d3c37/bin/pyenv-multiuser#L55

and then I checked in my resulting libexec folder for the modified `pyenv-init` file and I was still able to find a few references to `$PYENV_ROOT`:

https://github.com/pyenv/pyenv/blob/4405459f57bc0a0ea58223324f11599f6a9dbeee/libexec/pyenv-init#L193  
https://github.com/pyenv/pyenv/blob/4405459f57bc0a0ea58223324f11599f6a9dbeee/libexec/pyenv-init#L230  

So I fixed these lines to include `$PYENV_LOCAL_SHIM` instead and it seemed to have resolved my issues.

**Comment by macdub** [comment]
Ah I see what's going on here. Looks like there was a formatting change in the lines. I'll make an update to account for these.
